### ISSUE TITLE
get image from URL and store it in Array

### ISSUE THREAD

**Issue by josefantoni** [mohamede1945/PagedHorizontalView#1]
I am using framework PagedHorizontalView for Swift and I am trying to save IMAGE from URL to this ARRAY for using it in COLLECTION VIEW.

let items: [(image: String, label: String)] = [
        ("imageAssetName", "some random stuff")]
I tried to save image as Data but i then i realized i don't know what to do with it. Can anyone help me with this?

**Comment by mohamede1945** [comment]
This is actually out of the scope of the `PagedHorizontalView`.
