### ISSUE TITLE
Swift 4 compatibility : 'dynamic' var 'currentIndex' must also be '@objc'

### ISSUE THREAD

**Issue by olivereisenhut** [mohamede1945/PagedHorizontalView#10]
Hi thank you for you cool pod!

I am getting the following compile time error:  `'dynamic' var 'currentIndex' must also be '@objc'` while trying to compile with Swift 4. Would it break backwards compatibility to add this annotation?

**Comment by mohamede1945** [comment]
I'm no longer actively supporting it. But thanks for the fix.
