### ISSUE TITLE
When starting the app of your example,it start from small collection cell.

### ISSUE THREAD

**Issue by thihaaung6245** [mohamede1945/PagedHorizontalView#2]
First of all,Thank you so much for offering such a great library
But,I do have some problem.Don't know its bug or other.Mind take a look?

When I start load the app using my own image and your library,its start with small image cell.Then after passing 3 pages,it completely full and then page 1 and 2 become full again

Here is the project.
[PagedHorizontalView-master.zip](https://github.com/mohamede1945/PagedHorizontalView/files/275127/PagedHorizontalView-master.zip)

Here is the screenshot : 
![collectionviewpaging_1](https://cloud.githubusercontent.com/assets/10526402/15436136/58aeded2-1ee6-11e6-85e0-4aaa6bb72f56.gif)

Would you mind help me fix this?If I did something wrong,Any help is welcome.
If I pass this problem,I will start using this library with AlamofireImage for image slide show.

**Comment by mohamede1945** [comment]
The problem is actually a bug in interface builder, it tries to put the image and the label to be subviews to the cell itself not the `contentView` of the cell. If you printed the `subviews` of the cell. You will see

```
<UIView: 0x7f9b73529ca0; frame = (0 0; 375 189); gestureRecognizers = <NSArray: 0x7f9b7351e4b0>; layer = <CALayer: 0x7f9b7351d010>>,
<UIImageView: 0x7f9b73525020; frame = (0 0; 375 189); opaque = NO; autoresize = RM+BM; userInteractionEnabled = NO; layer = <CALayer: 0x7f9b7351e950>>,
<UILabel: 0x7f9b7352aa40; frame = (85 156; 205 33); text = 'The first image from spac...'; opaque = NO; autoresize = RM+BM; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x7f9b73521eb0>>
)
```

Actually, I recommend to re-create the cell with XIB file instead of storyboard.

**Comment by thihaaung6245** [comment]
Yeah,using the xib really solve the problem out.Thanks mate.
