### ISSUE TITLE
Is there anyway that i can implement slideshow on this collectionview?

### ISSUE THREAD

**Issue by thihaaung6245** [mohamede1945/PagedHorizontalView#4]
Any help with slide show support for every 5 second? and loop back to 1st index?

Also with infinite scroll?

Please I don't want to change another library because your library is perfect with auto layout.

**Comment by mohamede1945** [comment]
The slideshow can be implemented by a timer and a scroll to the next index of the collection view. The infinite scroll there is no support for it, but it shouldn't be hard to add to this library. You can use stackoverflow.com to ask there about how to implement it.

**Comment by mohamede1945** [comment]
You can extend the library and PR are welcomed!
