### ISSUE TITLE
Swift 2.3 and Swift 3 Support?

### ISSUE THREAD

**Issue by thihaaung6245** [mohamede1945/PagedHorizontalView#6]

**Comment by mohamede1945** [comment]
Sure, I'll do them next week.

**Comment by thihaaung6245** [comment]
Thanks.

**Comment by mohamede1945** [comment]
The library now supports swift 3. Sorry for late update.

**Comment by thihaaung6245** [comment]
Thanks...Actually it will be better,if that support Swift 2.3,too.Hope you implement when you free.

Regards
