### ISSUE TITLE
Cocoapods not working.

### ISSUE THREAD

**Issue by SeRG1k17** [mohamede1945/PagedHorizontalView#7]
Swift 3.0
Xcode 8
Manual installation works, Cocoapods:
![2017-02-27 11 33 59](https://cloud.githubusercontent.com/assets/13317173/23354249/51ad9bda-fce1-11e6-8ee5-55db79821010.png)

**Comment by mohamede1945** [comment]
Try to do `pod install` then clean build the entire project.

**Comment by SeRG1k17** [comment]
you can close it. Thanks
